### ISSUE TITLE
Shift-Click items out of chest

### ISSUE THREAD

**Issue by itami-aa** [HubertLipinski/ShiftClick#1]
When shift-clicking items out of a chest, the item replaces what is already in the hotbar slots with what was clicked on. Would be nice for it to go into the nearest empty inventory slot :) epic mod btw

**Comment by HubertLipinski** [comment]
@itami-aa Thanks for the feedback! I was able to implement this feature. 

Support for crate inventory is now available in version 1.0.0 (Pull request #2) with a few bug fixes that I was able to catch.  

If you have any other sugestions feel free to create another issue.
