### ISSUE TITLE
Mod not working when joining server or multiplayer

### ISSUE THREAD

**Issue by itami-aa** [HubertLipinski/ShiftClick#3]
title, cant shift click anything from inv/chest to hotbar or and vice versa, single works flawlessly however

**Comment by HubertLipinski** [comment]
Currently only single-player mode is supported. I will try to fix this in the near future.

**Comment by limoka** [comment]
Why did you put the `API.Server.World == null` check? That seems to be everything preventing the mod from working in MP. Your code is entirely client sided.
Your mod isn't supposed to be put on dedicated servers, but otherwise it works perfectly.

**Comment by limoka** [comment]
In fact I just tried using the mod while connected to dedicated server with that line removed, it works perfectly.

**Comment by HubertLipinski** [comment]
Thanks @limoka I just ran the test and it is as you said. I suppose this was overlooked by me when using the example code from the SDK.
