### ISSUE TITLE
Can't shift click items into cooking pot

### ISSUE THREAD

**Issue by limoka** [HubertLipinski/ShiftClick#4]
Like the title says, you cannot shift click food into cooking pot.

https://github.com/user-attachments/assets/e2a6d0e6-a597-4d43-a283-fff54c9d47e6

**Comment by limoka** [comment]
The same issue for furnaces

**Comment by HubertLipinski** [comment]
Thanks for pointing me to this issue. This is now fixed and will be released in v1.1.1.
